In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
from sklearn import svm
from sklearn.model_selection import train_test_split


## Construir y separar datos de entrenamiento y testeo

In [2]:
from src.svm_utils import build_samples 

GRASS = 0
COW = 1
SKY = 2
FARM = 3

grass_samples, grass_predictions = build_samples('./images/pasto.jpg', class_value = GRASS)
cow_samples, cow_predictions = build_samples('./images/vaca.jpg', class_value = COW)
sky_samples, sky_predictions = build_samples('./images/cielo.jpg', class_value = SKY)

X = np.append(np.append(grass_samples, cow_samples, axis=0), sky_samples, axis=0)
f_X = np.append(np.append(grass_predictions, cow_predictions, axis=0), sky_predictions, axis=0)

X_train, X_test, f_X_train, f_X_test = train_test_split(X, f_X, test_size=0.2, random_state=14)

print(grass_samples)


[[100 124 100]
 [106 131 109]
 [ 76 106  80]
 ...
 [133 154 111]
 [136 153 117]
 [129 149 121]]


## Clasificar la imagen campestre

In [3]:
from src.svm_utils import svm_classify_image 
# from src.svm_utils import build_samples
from datetime import datetime, timedelta

# now = datetime.now()

# svm_classify_image('./images/cow.jpg', X_train, f_X_train)

# later = datetime.now()

# # 6 minutikos en mi companera
# print(later - now)

## Obtener las matrizes de confusion y las precisiones

In [ ]:
from src.svm_utils import svm_get_precision 

def validate_c_values():
    c_values = np.arange(20)

    final_string = ''

    out_file = open('c_precision.csv', 'a')
    
    out_file.write('kernel,c value,train precision,test precision\n')
    
    for c in range(1, 50, 5):
        train_precision, test_precision = svm_get_precision(X_train, f_X_train, X_test, f_X_test, c)
        out_file.write(f'linear,{c},{train_precision},{test_precision}\n')

    out_file.close()
    
    
now = datetime.now()

validate_c_values()
        
later = datetime.now()
    
print(later - now)
    
def iterate_kernels():
    kernels = ['linear', 'poly', 'rbf']

    filename = 'kernel_precisoin.csv'
    final_string = ''

    for ker in kernels:
        train_precision, test_precision = svm_get_precision(c_value=1.0, kernel=ker)
        final_string += f'{1},{ker},{train_precision},{test_precision}\n'

    with open(filename, 'w') as fp:
        fp.write(final_string)
